### ISSUE TITLE
Create more informative error response body when password validation fails

### ISSUE THREAD

**Issue by zacklassetter** [GenerateNU/sac#141]
I was trying to create a new user using the create endpoint and kept receiving:

```
{
	"error": "failed to validate user"
}
```

We should consider giving a more detailed message on why validation failed. Not necessarily for all validation, but at least this case. i.e. "not enough special characters"

**Comment by garrettladley** [comment]
This could be due to the auth PR that just got merge in. David & I's big thing this weekend is getting testing to work with auth

**Comment by garrettladley** [comment]
Also need to handle this in the new api/vq/auth/update-password route- [see](https://github.com/GenerateNU/sac/blob/main/backend/src/services/auth.go#L92)

**Comment by garrettladley** [comment]
With #501, let's prioritize closing this
