### ISSUE TITLE
Make search better

### ISSUE THREAD

**Issue by michael-brennan2005** [GenerateNU/sac#296]
- [ ] General code refactor - more granular/specific errors, comments+documentation, more robust testing
- [ ] Search for events - adding filter support, adding semantic search
- [ ] Use OpenAI moderation api to prevent searching for hateful/sketchy stuff
- [ ] Metadata on all pinecone records for easier filtering
- [ ] Prevent SAC club from being shown, prevent clubs with a score < X from being shown

With these things implemented I think we would be in a good spot to then tackle tuning search results (prompt/embedding engineering, keyword extraction, hybrid search, etc.)

**Comment by garrettladley** [comment]
should these be split into sub issues? as sub issues, we expand the contribution surface so more people can contribute to getting this done
