### ISSUE TITLE
Fix: Error duplication for models

### ISSUE THREAD

**Issue by DOOduneye** [GenerateNU/sac#57]
Currently we implement a new set of errors for each model, e.g `FailedToValidateX`, instead we can generate the `X` from a model base. 

Seeking to implement: `&errors.users.FailedToValidate`

**Comment by garrettladley** [comment]
With the limitations of Go, I am unaware of a way to reduce this duplication. I agree and I am not 100% satisfied with the current state of error handling. However, not sure if there is a better way after talking with @brianreicher. Going to close as not planned for right now but we can do an alternative prototyping session this weekend!

**Comment by garrettladley** [comment]
With the limitations of Go, I am unaware of a way to reduce this duplication. I agree and I am not 100% satisfied with the current state of error handling. However, not sure if there is a better way after talking with @brianreicher. Going to close as not planned for right now but we can do an alternative prototyping session this weekend!
