### ISSUE TITLE
fix: events

### ISSUE THREAD

**Issue by garrettladley** [GenerateNU/sac#669]

**Comment by garrettladley** [comment]
(ideally) closing this ticket will close #668

**Comment by garrettladley** [comment]
from Sat 5/4 Meeting w/ @alderwhiteford

**Event**
- start_time
- end_time
- start_date
- end_date
- recurrence (str/binary proto that represents weekly, biweekly, monthly, days_of_week)
- termination_date
- is_draft
- description
- []Tag
- title
- cover_image
- event_type: hybrid | in-person | online
- is_public
- is_archived
- Optional<calendar_integration_id> (fkey)

in create event series request body: termination_date

**Comment by alderwhiteford** [comment]
Tables:

Event Series
- id
- created_at
- modified_at

Event
- event_series_id?
- ...all other fields

If an event with a series_id is updated, you can pass in a flag to update this one event or all events in the series (boolean).

**Comment by DOOduneye** [comment]
I wasn't at the meeting and this may have already been spoken about but how do we handle recurring events but they skip a week or something similar
