### ISSUE TITLE
backend: create club request body

### ISSUE THREAD

**Issue by garrettladley** [GenerateNU/sac#777]
create club request body should not include the user id. this should be fetched automatically through something like a middleware (maybe reuse the logic behind the `/me` route). also, maybe membership of a club could automatically be handled with some gorm magic

**Comment by DOOduneye** [comment]
Club eboard will never make their own club so there needs to be a way to point a club "creator" (which is currently under our design just the first admin of a club)

**Comment by garrettladley** [comment]
i see, will close this
