### ISSUE TITLE
🧹 chore: more configurable oauth settings

### ISSUE THREAD

**Issue by garrettladley** [GenerateNU/sac#932]
@alderwhiteford, should the redirect uri be hardcoded? what is it in reference to? frontend uri? backend uri?

`RedirectURI:  "http://localhost:3000",`

**Comment by garrettladley** [comment]
see [backend/config/oauth_google.go](https://github.com/GenerateNU/sac/blob/main/backend/config/oauth_google.go) and [backend/config/oauth_outlook.go](https://github.com/GenerateNU/sac/blob/main/backend/config/oauth_outlook.go)

**Comment by alderwhiteford** [comment]
redirectURI is where the user is redirected to on the frontend after authenticating with the oauth client. It should be hardcoded for local and production

**Comment by garrettladley** [comment]
but the port might not always be 3000? we might set to port 0 to get a dynamic port allocation
